'use strict';

/**
 * Provides an interface to convert between calling codes and country ids.
 */
angular.module('mk.Services')
    .factory('mkCountries', function() {

        // note: some countries have the same calling code, e.g. USA and Canada
        var countries = [
            {id: 1, callingCode: '91', name: 'India', numberRegex: /^\d{10}$/},
            {id: 2, callingCode: '1', name: 'USA'},
            {id: 3, callingCode: '93', name: 'Afghanistan'},
            {id: 4, callingCode: '355', name: 'Albania'},
            {id: 5, callingCode: '213', name: 'Algeria'},
            {id: 6, callingCode: '54', name: 'Argentina'},
            {id: 7, callingCode: '61', name: 'Australia'},
            {id: 8, callingCode: '43', name: 'Austria'},
            {id: 9, callingCode: '973', name: 'Bahrain'},
            {id: 10, callingCode: '880', name: 'Bangladesh'},
            {id: 11, callingCode: '32', name: 'Belgium'},
            {id: 12, callingCode: '975', name: 'Bhutan'},
            {id: 13, callingCode: '591', name: 'Bolivia'},
            {id: 14, callingCode: '267', name: 'Botswana'},
            {id: 15, callingCode: '55', name: 'Brazil'},
            {id: 16, callingCode: '673', name: 'Brunei'},
            {id: 17, callingCode: '359', name: 'Bulgaria'},
            {id: 18, callingCode: '226', name: 'Burkina Faso'},
            {id: 19, callingCode: '855', name: 'Cambodia'},
            {id: 20, callingCode: '237', name: 'Cameroon'},
            {id: 21, callingCode: '1', name: 'Canada'},
            {id: 22, callingCode: '235', name: 'Chad'},
            {id: 23, callingCode: '56', name: 'Chile'},
            {id: 24, callingCode: '86', name: 'China'},
            {id: 25, callingCode: '57', name: 'Colombia'},
            {id: 26, callingCode: '269', name: 'Comoros'},
            {id: 27, callingCode: '506', name: 'Costa Rica'},
            {id: 29, callingCode: '385', name: 'Croatia'},
            {id: 30, callingCode: '53', name: 'Cuba'},
            {id: 31, callingCode: '357', name: 'Cyprus'},
            {id: 32, callingCode: '420', name: 'Czech Republic'},
            {id: 33, callingCode: '45', name: 'Denmark'},
            {id: 34, callingCode: '20', name: 'Egypt'},
            {id: 35, callingCode: '503', name: 'El Salvador'},
            {id: 36, callingCode: '372', name: 'Estonia'},
            {id: 37, callingCode: '251', name: 'Ethiopia'},
            {id: 38, callingCode: '679', name: 'Fiji'},
            {id: 39, callingCode: '358', name: 'Finland'},
            {id: 40, callingCode: '33', name: 'France'},
            {id: 41, callingCode: '995', name: 'Georgia'},
            {id: 42, callingCode: '49', name: 'Germany'},
            {id: 43, callingCode: '233', name: 'Ghana'},
            {id: 44, callingCode: '30', name: 'Greece'},
            {id: 45, callingCode: '852', name: 'Hong Kong'},
            {id: 46, callingCode: '36', name: 'Hungary'},
            {id: 47, callingCode: '354', name: 'Iceland'},
            {id: 48, callingCode: '62', name: 'Indonesia'},
            {id: 49, callingCode: '964', name: 'Iraq'},
            {id: 50, callingCode: '98', name: 'Iran'},
            {id: 51, callingCode: '972', name: 'Israel'},
            {id: 52, callingCode: '39', name: 'Italy'},
            {id: 53, callingCode: '81', name: 'Japan'},
            {id: 54, callingCode: '254', name: 'Kenya'},
            {id: 55, callingCode: '856', name: 'Laos'},
            {id: 56, callingCode: '371', name: 'Latvia'},
            {id: 57, callingCode: '961', name: 'Lebanon'},
            {id: 58, callingCode: '266', name: 'Lesotho'},
            {id: 59, callingCode: '218', name: 'Libya'},
            {id: 60, callingCode: '352', name: 'Luxembourg'},
            {id: 61, callingCode: '853', name: 'Macau'},
            {id: 62, callingCode: '261', name: 'Madagascar'},
            {id: 63, callingCode: '265', name: 'Malawi'},
            {id: 64, callingCode: '60', name: 'Malaysia'},
            {id: 65, callingCode: '960', name: 'Maldives'},
            {id: 66, callingCode: '223', name: 'Mali'},
            {id: 67, callingCode: '356', name: 'Malta'},
            {id: 68, callingCode: '230', name: 'Mauritius'},
            {id: 69, callingCode: '52', name: 'Mexico'},
            {id: 70, callingCode: '377', name: 'Monaco'},
            {id: 71, callingCode: '976', name: 'Mongolia'},
            {id: 72, callingCode: '382', name: 'Montenegro'},
            {id: 73, callingCode: '212', name: 'Morocco'},
            {id: 74, callingCode: '258', name: 'Mozambique'},
            {id: 75, callingCode: '95', name: 'Myanmar'},
            {id: 76, callingCode: '264', name: 'Namibia'},
            {id: 77, callingCode: '31', name: 'Netherlands'},
            {id: 78, callingCode: '977', name: 'Nepal'},
            {id: 79, callingCode: '64', name: 'New Zealand'},
            {id: 80, callingCode: '505', name: 'Nicaragua'},
            {id: 81, callingCode: '234', name: 'Nigeria'},
            {id: 82, callingCode: '850', name: 'North Korea'},
            {id: 83, callingCode: '47', name: 'Norway'},
            {id: 84, callingCode: '92', name: 'Pakistan'},
            {id: 85, callingCode: '507', name: 'Panama'},
            {id: 86, callingCode: '595', name: 'Paraguay'},
            {id: 87, callingCode: '51', name: 'Peru'},
            {id: 88, callingCode: '63', name: 'Philippines'},
            {id: 89, callingCode: '48', name: 'Poland'},
            {id: 90, callingCode: '351', name: 'Portugal'},
            {id: 91, callingCode: '974', name: 'Qatar'},
            {id: 92, callingCode: '40', name: 'Romania'},
            {id: 93, callingCode: '7', name: 'Russia'},
            {id: 94, callingCode: '250', name: 'Rwanda'},
            {id: 95, callingCode: '966', name: 'Saudi Arabia'},
            {id: 96, callingCode: '221', name: 'Senegal'},
            {id: 97, callingCode: '248', name: 'Seychelles'},
            {id: 98, callingCode: '65', name: 'Singapore', numberRegex: /^[689]\d{7}$/},
            {id: 99, callingCode: '421', name: 'Slovakia'},
            {id: 100, callingCode: '386', name: 'Slovenia'},
            {id: 101, callingCode: '27', name: 'South Africa'},
            {id: 102, callingCode: '82', name: 'South Korea'},
            {id: 103, callingCode: '34', name: 'Spain'},
            {id: 104, callingCode: '94', name: 'Sri Lanka'},
            {id: 105, callingCode: '268', name: 'Swaziland'},
            {id: 106, callingCode: '46', name: 'Sweden'},
            {id: 107, callingCode: '41', name: 'Switzerland'},
            {id: 108, callingCode: '886', name: 'Taiwan'},
            {id: 109, callingCode: '992', name: 'Tajikistan'},
            {id: 110, callingCode: '255', name: 'Tanzania'},
            {id: 111, callingCode: '66', name: 'Thailand'},
            {id: 112, callingCode: '90', name: 'Turkey'},
            {id: 113, callingCode: '971', name: 'UAE'},
            {id: 114, callingCode: '44', name: 'UK'},
            {id: 115, callingCode: '58', name: 'Venezuela'},
            {id: 116, callingCode: '84', name: 'Vietnam'},
            {id: 117, callingCode: '260', name: 'Zambia'},
            {id: 118, callingCode: '263', name: 'Zimbabwe'},
            {id: 119, callingCode: '353', name: 'Ireland'}
        ];

        return {
            countries: countries,
            idToCountry: _.indexBy(countries, 'id'),
            callingCodeToCountry: _.indexBy(countries, 'callingCode'),
            validatePhoneNumber: function(callingCode, phoneNumber) {
                return !!phoneNumber.replace(/\s/g, '').match(_.indexBy(countries, 'callingCode')[callingCode].numberRegex)
            }
        };
    });